apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-repeaters-net-api
spec:
  rules:
  - host: repeaters.dszymanski.pl
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: repeaters-net-api
            port:
              number: 80