# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Vue app

on:
  push:
    branches: [ "master" ]
    paths:
      - Web/**
      - .github/workflows/node.js.yml
    
  pull_request:
    branches: [ "master" ]
    paths:
      - Web/**
      - .github/workflows/node.js.yml

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-vue

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Web

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        working-directory: ./Web
        node-version: 20.x
        cache: 'npm'
        cache-dependency-path: 'Web/package-lock.json'
    - run: npm ci
    - run: npm run build --if-present
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./Web
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
